### PR TITLE
Backspace in inserts (#24)

### PR DESCRIPTION
**Pull request by sourrust**
lastInsert now grabs the text before and after backspaces.

### CODE REVIEW

**Comment by misfo** [comment]
Wow. This is good stuff. I'll take a closer look when I'm at a computer, but it looks good to me. Thanks for adding the tests

**Comment by sourrust** [comment]
Alright, I think this will close the concerns you brought up.

**Comment by misfo** [comment]
This is really close.  Thanks for all your hard work.  I put a few more line notes into the commit for some of the last bits that need to be accounted for.

**Comment by sourrust** [comment]
It took awhile, but I think got the last two issues

**Comment by misfo** [comment]
Noice!  All merged in.  Thanks again

**Pull request closed without merging**
