### PR TITLE
Issue 10

### PR DESCRIPTION
**Pull request by sourrust**
Feature request in issue #10
Visual mode `o`, it also does the same for `O` since we don't have visual block mode yet.

### CODE REVIEW

**Comment by misfo** [comment]
I like it. Looks perfect in characterwise visual mode. In linewise, however, pressing o twice doesnt put the cursor back where it started...

**Comment by sourrust** [comment]
This should fix it, however I noticed, when both anchor and lead are the same, linewise selection disappears visually, but really is still there.

**Comment by misfo** [comment]
Yeah, that's because [this hack](https://github.com/misfo/jim/blob/master/src/ace.coffee#L197-210) isn't used in this patch.  Unfortunately we'll have to keep track of the position of the selection anchor in the [modeState](https://github.com/misfo/jim/blob/master/src/jim.coffee#L25) so that we can use that hack to set the selection anchor (when linewise) and still know where to put the cursor when the user hits `o` or `O`.

**Comment by sourrust** [comment]
Alright looks like everything is good, thanks for telling me about `modeState`.

**Comment by sourrust** [comment]
Never mind my response to your comment, I think I understand what you were getting at after messing around a bit more. I think this is what you asked for.

**Comment by misfo** [comment]
Looks good. Thanks!

**Pull request merged**
